### ISSUE TITLE
无法使用？是国人？

### ISSUE THREAD

**Issue by JiangQinZhe** [imsheng/bitter-gourd#1]
Fatal error: Label 'var_5263a6c9fd8066fb86a8ba12b69316c3' already defined
诸如此类，用这个加密器有什么限制吗？
它是否不支持html与php的混合代码，或不支持的语法？

**Comment by imsheng** [comment]
没有什么限制，未测试过html+php的文件，在疫情期间无聊做出来的，这两天我去试一下。

**Comment by JiangQinZhe** [comment]
这么晚了还在 码？

**Comment by imsheng** [comment]
方便提供一下有问题的某个文件吗？

**Comment by JiangQinZhe** [comment]
可以的，等会儿发个蓝奏链接给你

**Comment by JiangQinZhe** [comment]
https://www.lanzous.com/iab88fc
我提供了两对源码，一对是加密后有效运行的，另一对是报错的，仅供参考。

**Comment by imsheng** [comment]
1，我大该知道是什么问题了，但我只有星期天才有时间改进，
2，暂时可以去 src/Command/RunCommand.php 这文件下把102行删掉，这样可以不处理 if 语法了。https://github.com/imsheng/bitter-gourd/blob/master/src/Command/RunCommand.php#L102

**Comment by JiangQinZhe** [comment]
给几点建议：
1、在原混淆基础上加入编码【二进制】，使代码不能被阅读，修改。
2、不要保留格式！！！可以把它缩成一行（我自己已经改进了）
3、可以尝试下虚拟机（我之前尝试过，后来放弃了）

瞅瞅改改？

**Comment by imsheng** [comment]
1，如果使用二进制，就要用到扩展，这样就违反了“无依赖”原则了，市面上很多同类的加密软件了
2，很多IDE都可以一键、批量美化代码，所以没什么意义。
3，虚拟机？如里想到什么特别诡异的方式改写原代码的 可以给留言给我。

ps：这项目的出发点是要无依赖，适合所有框架(tp,yii,laravel,ci)，用特别的方式改写原代码，用来防止别人二次开发。

**Comment by JiangQinZhe** [comment]
虚拟机加密，不知道你有没有听说过？

**Comment by imsheng** [comment]
没听说过，能发点资料来参考参考？

**Comment by JiangQinZhe** [comment]
我要继上次的说说：
1、混淆二进制代码不一定需要扩展组件，现在市面上最好的组件加密（如SG11，IC10等），都并没有用扩展。混淆的作用在于使破解者难以阅读，如替换变量、函数名为 0x80-0xff 的不可读字符，从而加大破解难度。当然压缩，也是一样。
2、建议使用常量池等方法，对代码中的函数及字符串进行混淆。
3、多种加密的资料在此。（SG11，mfenc_crane，mzphp，z5）
https://www.lanzous.com/iannrbe

**Comment by imsheng** [comment]
感谢. 我仔细参考一下
