### ISSUE TITLE
楼主 可以教一下使用使用方法嘛

### ISSUE THREAD

**Issue by 27443114** [imsheng/bitter-gourd#3]
谢谢

**Comment by imsheng** [comment]
git clone https://github.com/imsheng/bitter-gourd.git

cd bitter-gourd

composer install

php bin/console -p/my_project   整个目录下的php
或
php bin/console -f/test.php     单个文件

这就是使用方法啊

顺便提一下有一个bug还没修复，暂时可以去 src/Command/RunCommand.php 这文件下把102行删掉

**Comment by 27443114** [comment]
E:\phpstudy_pro\WWW>php bin/console -f/test.php
PHP Warning:  require(E:\phpstudy_pro\WWW\bin/../vendor/autoload.php): failed to open stream: No such file or directory in E:\phpstudy_pro\WWW\bin\console on line 9

Warning: require(E:\phpstudy_pro\WWW\bin/../vendor/autoload.php): failed to open stream: No such file or directory in E:\phpstudy_pro\WWW\bin\console on line 9
PHP Fatal error:  require(): Failed opening required 'E:\phpstudy_pro\WWW\bin/../vendor/autoload.php' (include_path='.;C:\php\pear') in E:\phpstudy_pro\WWW\bin\console on line 9

Fatal error: require(): Failed opening required 'E:\phpstudy_pro\WWW\bin/../vendor/autoload.php' (include_path='.;C:\php\pear') in E:\phpstudy_pro\WWW\bin\console on line 9
这个怎么解决

**Comment by imsheng** [comment]
composer install
这个命令运行了吗？

运行后  目录下会有vendor这个文件夹

**Comment by imsheng** [comment]
还有就是文件要全地址，
windows:  c:/xxx/xxx/test.php
linux  /test.php

**Comment by 27443114** [comment]
composer install这个命令运行后目录还是没vendor

**Comment by imsheng** [comment]
![企业微信截图_20200324154007](https://user-images.githubusercontent.com/10435075/77400232-ce0b3200-6de5-11ea-9144-83df8ffadbdb.png)

要在目录里执行，然后看看执行正常不正常

然后暂时去 src/Command/RunCommand.php 这文件下把102行删掉。（bug)

**Comment by 27443114** [comment]
![捕获](https://user-images.githubusercontent.com/44933758/77421560-ffe0c080-6e06-11ea-83fa-ccc3042ae0ec.PNG)
也不欧克 我还Linux还是提示这个

**Comment by 27443114** [comment]
换

**Comment by imsheng** [comment]
git clone https://github.com/imsheng/bitter-gourd.git    下载包
cd bitter-gourd     转到包目录下   一定在要转在包的目录下
然后再往下执行

要不你先在windows下试一下

**Comment by 27443114** [comment]
![捕获](https://user-images.githubusercontent.com/44933758/77440423-404e3780-6e23-11ea-9d16-dd014cc6e8d5.PNG)
我现在搞不定。。。Linux window我都搞不定

**Comment by imsheng** [comment]
如果你方便的话  你把宝塔账号密码发到我邮箱吧  707470341@qq.com

**Comment by imsheng** [comment]
要么加我QQ  我远程一次给你看看

**Comment by 27443114** [comment]
好的 我加您QQ了 大晚上的要不您可以明天教教俺

**Comment by JiangQinZhe** [comment]
你连composer都没安装，基本入门！！！

**Comment by JiangQinZhe** [comment]
宝塔面板会禁用部分函数，要开放，才可以使用。你看看你在用composer install安装的时候，有没有警告warning，还有情况是没有安装composer或是默认版本不对，这个加密程序好像需要php73以上的版本，注意所有错误提示和警告

**Comment by imsheng** [comment]
嗯，是新手
