### ISSUE TITLE
有详细使用说明吗，提示错误

### ISSUE THREAD

**Issue by myfengstyle** [imsheng/bitter-gourd#4]
有详细使用说明吗，运行php bin/console -h
or
php bin/console -p/my_project
or
php bin/console -f/test.php都提示错误

**Comment by imsheng** [comment]
要全地址，c:\xxx\xxx\.php 这样

**Comment by imsheng** [comment]
有一些bug修复了，要重新下载新版本

**Comment by myfengstyle** [comment]
谢谢
