### ISSUE TITLE
加密问题

### ISSUE THREAD

**Issue by 27443114** [imsheng/bitter-gourd#6]
执行了加密的命令 然后去查看加密 并没加密

**Comment by imsheng** [comment]
只加密目录下的php文件。

**Comment by 27443114** [comment]
可是执行了命令 没效果

**Comment by imsheng** [comment]
可否截个图来看看

**Comment by 27443114** [comment]
![捕获](https://user-images.githubusercontent.com/44933758/84509519-67b3f280-acf6-11ea-94ba-5129387623bb.PNG)

**Comment by imsheng** [comment]
方便把文件发给我试一下吗？ 707470341@qq.com

**Comment by 27443114** [comment]
是加密什么文件都加密不了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "im sheng"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 凌晨1:17
收件人: "imsheng/bitter-gourd"<bitter-gourd@noreply.github.com&gt;; 
抄送: "小布"<27443114@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [imsheng/bitter-gourd] 加密问题 (#6)





 
方便把文件发给我试一下吗？ 707470341@qq.com

**Comment by imsheng** [comment]
可能没在linux下测试过，这几天试一下

**Comment by 27443114** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "im sheng"<notifications@github.com&gt;; 
发送时间: 2020年6月13日(星期六) 下午2:05
收件人: "imsheng/bitter-gourd"<bitter-gourd@noreply.github.com&gt;; 
抄送: "小布"<27443114@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [imsheng/bitter-gourd] 加密问题 (#6)





 
可能没在linux下测试过，这几天试一下

**Comment by andhub-cn** [comment]
应该是linux下无法加密 很久前就是这个问题

**Comment by imsheng** [comment]
![微信截图_20200704150916](https://user-images.githubusercontent.com/10435075/86507147-7038ae00-be08-11ea-9db3-bf2a72b025b6.png)
已经在 linux 里测试过了，没发现有什么问题，看一下是否于你们操作的不同 @andhub-cn @27443114
